### ISSUE TITLE
Possible bug in CglPreProcess::preProcessNonDefault in version 2.10.5.

### ISSUE THREAD

**Issue by DenisSbragion** [coin-or/Cgl#52] opened 2020-03-17 14:26 UTC
Hello,

while digging into the CBC code I found somehting which appears to me as a bug. 

Starting from line 1125, in the function:

OsiSolverInterface *
CglPreProcess::preProcessNonDefault(OsiSolverInterface &model,
  int makeEquality, int numberPasses,
  int tuning)

at line 1162:

originalModel_ = &model;

At line 1206:

startModel_ = originalModel_;

At line 1222:

delete startModel_;

But this way startModel_ has never been allocated.

Hope it helps.

**Comment by DenisSbragion** [comment] 2020-03-30 12:50
> I rather see a problem that if line 1206 gets executed (`numberPasses==99`), then line 1222 will delete `originalModel_` (which `&model` and was passed in by the caller), so line 1223 will fail.

Sorry if my message wasn't clear. This is exactly what I meant.

**Comment by jjhforrest** [comment] 2020-03-30 13:32
Denis,

If the presolve called at line 1204 says the problem is feasible, then 
the code returns before getting to 1222.  If the problem is infeasible 
you would not enter preprocessing at all.

However I will amend so that if infeasible the code returns NULL before 
1222.

John Forrest

**Comment by svigerske** [comment] 2020-03-30 14:05
Fixed in 4bc9a6a.

**Closed as completed by svigerske** 2020-03-30 14:05 UTC
